assets: /mnt/data/LIBERO/libero/libero/assets
bddl_files: /mnt/data/LIBERO/libero/libero/bddl_files
benchmark_root: /mnt/data/LIBERO/libero/libero
datasets: /mnt/data/SimVLA/datasets
init_states: /mnt/data/LIBERO/libero/libero/init_files
